theme: jekyll-theme-minimal
title: <br> <span style="color:grey"> CVPR@Paris 2025 6<sup>th</sup> of June<br></span>
description: ''
github:
  is_user_page: false
  is_project_page: false
logo: /docs/assets/logo_CVPR.png
