theme: jekyll-theme-minimal
title: <br> <span style="color:grey"> CVPR@Paris 2025 June 6<sup>th</sup><br></span>
description: ''
github:
  is_user_page: false
  is_project_page: false
logo: /docs/assets/logo_CVPR.png
