theme: jekyll-theme-minimal
title: <br> <span style="color:grey"> 6<sup>th</sup> of June <br> Sorbonne Université</span>
description: ''
github:
  is_user_page: false
  is_project_page: false
logo: /docs/assets/logo_CVPR.png
